### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by ramirezaa** [ethz-asl/libnabo#30]
Hello it seemed like everything installed correctly, but when I try to compile the "trivial.cpp" file, I get the following undefined reference errors:

/tmp/ccx3BoPz.o: In function main': nn.cpp:(.text+0x83): undefined reference toNabo::NearestNeighbourSearch::createKDTreeLinearHeap(Eigen::Matrix const&, int, unsigned int, Nabo::Parameters const&)'

nn.cpp:(.text+0x10d): undefined reference to `Nabo::NearestNeighbourSearch::knn(Eigen::Matrix const&, Eigen::Matrix&, Eigen::Matrix&, int, float, unsigned int, float) const'

Can you encountered this bug before?

I already had Eigen and Boost installed, so I do not know what else is required

**Comment by simonlynen** [comment]
@ramirezaa how do you compile this file? Usually this should be done as part of the normal build process so if you say "everything installed correctly" then I presume the examples were also build. Can you let me know the command you want to use to build the example?

**Comment by ramirezaa** [comment]
@simonlynen I compile with the following command:

````
g++ trivial.cpp -o runTrivial
````

The examples were built succesfully, but when I try to compile the errors pop up. Did I forget to include the name of the library?

**Comment by simonlynen** [comment]
You will need to link to the library libnabo too. Prefer to use the cmake
build system which should build the example for you.

**Comment by ramirezaa** [comment]
I can compile trivial.cpp & usage.cpp with Cmake. Although, I'm trying to compile my own program by properly linking to the correct library. I do the following:

```
g++ myFile.cpp -L/usr/local/lib -lnabo
```

But I still get errors. What is the best way to compile my own program?

**Comment by simonlynen** [comment]
What are the errors you get now?

**Comment by ramirezaa** [comment]
I actually get a long list of errors, but here since it seems to simply repeat here is the first part:

```
/usr/local/lib/libnabo.a(kdtree_cpu.cpp.o): In function `std::vector<float, std::allocator<float> >::_M_fill_initialize(unsigned long, float const&)':
/usr/include/c++/4.8/bits/stl_vector.h:1216: undefined reference to `GOMP_loop_guided_start'
/usr/local/lib/libnabo.a(kdtree_cpu.cpp.o): In function `Nabo::KDTreeUnbalancedPtInLeavesImplicitBoundsStackOpt<float, Nabo::IndexHeapBruteForceVector<int, float> >::knn(Eigen::Matrix<float, -1, -1, 0, -1, -1> const&, Eigen::Matrix<int, -1, -1, 0, -1, -1>&, Eigen::Matrix<float, -1, -1, 0, -1, -1>&, int, float, unsigned int, float) const [clone ._omp_fn.2]':
/home/aramirez39/Desktop/libnabo/nabo/kdtree_cpu.cpp:302: undefined reference to `GOMP_loop_guided_next'
/home/aramirez39/Desktop/libnabo/nabo/kdtree_cpu.cpp:299: undefined reference to `GOMP_loop_end'
/usr/local/lib/libnabo.a(kdtree_cpu.cpp.o): In function `Nabo::KDTreeUnbalancedPtInLeavesImplicitBoundsStackOpt<float, Nabo::IndexHeapBruteForceVector<int, float> >::knn(Eigen::Matrix<float, -1, -1, 0, -1, -1> const&, Eigen::Matrix<int, -1, -1, 0, -1, -1>&, Eigen::Matrix<float, -1, -1, 0, -1, -1>&, Eigen::Matrix<float, -1, 1, 0, -1, 1> const&, int, float, unsigned int) const [clone ._omp_fn.3]':
/home/aramirez39/Desktop/libnabo/nabo/kdtree_cpu.cpp:329: undefined reference to `GOMP_loop_guided_start'
/home/aramirez39/Desktop/libnabo/nabo/kdtree_cpu.cpp:334: undefined reference to `GOMP_loop_guided_next'
/home/aramirez39/Desktop/libnabo/nabo/kdtree_cpu.cpp:329: undefined reference to `GOMP_loop_end'
```

**Comment by simonlynen** [comment]
You will need to compile with openmp support or disable openmp in libnabo:

### Compile your code with openMP:
```
g++ myFile.cpp -fopenmp -L/usr/local/lib -lnabo -lgomp
```

### Disable openMP in libnabo
Comment this line: https://github.com/ethz-asl/libnabo/blob/master/CMakeLists.txt#L52

**Comment by ramirezaa** [comment]
Thank you! That fixed it! I'll compile with openmp.
