### ISSUE TITLE
MinGW: Do not include gomp

### ISSUE THREAD

**Issue by lofidevops** [ethz-asl/libnabo#37]
**Steps to reproduce:**

Build on a MinGW platform

**What should happen:**

Build successful.

**What happens instead:**

Fails due to dependency on GOMP/libgomp.

**Notes:**

MinGW is unusual in that it is both a GCC platform and a Windows platform. Unlike other GCC platforms, it is not guaranteed that GOMP is installed (afaik no MinGW installation currently includes GOMP).

Thus the CMake logic to include GOMP should be something like:

```
if (platform == GCC) and (platform != MinGW):
    include gomp
```

**Workaround:**

https://github.com/kwill/libnabo/commit/1e1335163bfd4e3ea679d17108efcf1d6324174c

Edit CMake files so that gomp is never included. This is obviously not a long-term solution.

**Comment by simonlynen** [comment]
We would just need to change the cmake to also check for mingw. Could you
open a pull-request that adds this check to cmake? Since I dont have a
setup to test this.

No further changes to the code should be needed.

Thanks

**Comment by lofidevops** [comment]
See https://github.com/ethz-asl/libnabo/pull/66
