### ISSUE TITLE
compiling on Windows 10 using Visual Studio 2013 fails...

### ISSUE THREAD

**Issue by drhalftone** [ethz-asl/libnabo#47]
Error   1   error D8021: invalid numeric argument '/Wextra' C:\Users\Dr. Daniel L. Lau\Developer\libnabo\build\cl   nabo

I read about this error online, and the advice was to remove the /Wextra in the cmakelists.txt.

**Comment by simonlynen** [comment]
yes, you can remove this line. It basically triggers an error for compiler warnings.
