### ISSUE TITLE
Indentation rule for libnabo?

### ISSUE THREAD

**Issue by HannesSommer** [ethz-asl/libnabo#54]
I couldn't find any specification on this matter and the current state reflects some shift away from the original tab indentation. 

Before things get worse this should be clarified for some future. Hence, this issue.

The majority of the files currently and the history of the mixed files clearly is in favour of **tab** indentation in all source files.

It seems to me, it is @stephanemagnenat who should decide this, unless he wants to open this question for discussion.

**Comment by pomerlef** [comment]
I just finished to watch Silicon Valley season 3 and this scene seems very relevant:
https://www.youtube.com/watch?v=SsoOG6ZeyUI

That being said, if I recall well the idea was to keep it relax on those rules as long as it is consistent within one subblock and that it is readable (yeah, I know, those latin people...). In the event that it was going out of control, we would use a script to reformat.

So it's up to you guys if you want to formalize a set of rules and enforce them. @stephanemagnenat won't hold anybody responsible for that ;)

**Comment by stephanemagnenat** [comment]
I'm in holidays now, I'll have a look and thought in two weeks. Can we wait until then?

**Comment by simonlynen** [comment]
Nabo uses tabs so we should stick to this if we want to make it project
wide consistent. Otherwise please make it consistent within this file and
we can take a pass later to reformat all of it if desired.

**Comment by HannesSommer** [comment]
Thanks for the link @pomerlef - that made your point quite clear :).

@stephanemagnenat , sure this can wait - nothing is blocked! Have a nice vacation!

@simonlynen , it's merged already - somehow consistent. With all possible further actions concerning white spaces I'd just wait for this issue being settled.

**Comment by stephanemagnenat** [comment]
I agree we should stick with tabs. When I wrote nabo, I used indentation with tabs with 4 spaces for a tab in the editor. We should probably set modelines for this style for common editors.

**Comment by HannesSommer** [comment]
PR #55 should clean up most of the so far grown white space chaos. Any objections?

**Comment by HannesSommer** [comment]
Closing this after merging #55.
