### ISSUE TITLE
CMake Error: Internal CMake error, TryCompile configure of cmake failed

### ISSUE THREAD

**Issue by mounaattia** [ethz-asl/libnabo#56]
Hello,
I want to compile libnabo. I have used VS 2010 in win32. When I run CMake I have this error

> 
The C compiler identification is MSVC 16.0.40219.1
The CXX compiler identification is MSVC 16.0.40219.1
Check for working C compiler: C:/Program Files/Microsoft Visual Studio 10.0/VC/bin/cl.exe
Check for working C compiler: C:/Program Files/Microsoft Visual Studio 10.0/VC/bin/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio 10.0/VC/bin/cl.exe
Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio 10.0/VC/bin/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
Boost version: 1.49.0
CMake Warning (dev) at C:/Users/ACER/Downloads/cmake-3.7.1-win32-x86/cmake-3.7.1-win32-x86/share/cmake-3.7/Modules/FindOpenMP.cmake:179 (if):
  if given arguments:

    "TRUE"

  An argument named "TRUE" appears in a conditional statement.  Policy
  CMP0012 is not set: if() recognizes numbers and boolean constants.  Run
  "cmake --help-policy CMP0012" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  C:/Users/ACER/Downloads/cmake-3.7.1-win32-x86/cmake-3.7.1-win32-x86/share/cmake-3.7/Modules/FindOpenMP.cmake:224 (_OPENMP_GET_SPEC_DATE)
  CMakeLists.txt:54 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Users/ACER/Downloads/cmake-3.7.1-win32-x86/cmake-3.7.1-win32-x86/share/cmake-3.7/Modules/FindOpenMP.cmake:179 (if):
  if given arguments:

    "TRUE"

  An argument named "TRUE" appears in a conditional statement.  Policy
  CMP0012 is not set: if() recognizes numbers and boolean constants.  Run
  "cmake --help-policy CMP0012" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  C:/Users/ACER/Downloads/cmake-3.7.1-win32-x86/cmake-3.7.1-win32-x86/share/cmake-3.7/Modules/FindOpenMP.cmake:266 (_OPENMP_GET_SPEC_DATE)
  CMakeLists.txt:54 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

OpenCL disabled, not looking for it
ANN not found, disabling it in benchmarks
FLANN not found, disabling it in benchmarks
CMake Error at D:/Project/build/tests/CMakeFiles/CMakeTmp/CMakeLists.txt:11 (add_definitions):
  Syntax error in cmake code at

    D:/Project/build/tests/CMakeFiles/CMakeTmp/CMakeLists.txt:11

  when parsing string

    -IC:\Program

  Invalid character escape '\P'.

CMake Error at D:/Project/build/tests/CMakeFiles/CMakeTmp/CMakeLists.txt:11 (add_definitions):
  Syntax error in cmake code at

    D:/Project/build/tests/CMakeFiles/CMakeTmp/CMakeLists.txt:11

  when parsing string

    Files\Eigen

  Invalid character escape '\E'.

CMake Error: Internal CMake error, TryCompile configure of cmake failed
Configuring incomplete, errors occurred!
See also "D:/Project/build/CMakeFiles/CMakeOutput.log".

> 
there is any one who can help me
thank you

**Comment by dymczykm** [comment]
@mounaattia your error seems to be related to the path in: ```D:/Project/build/tests/CMakeFiles/CMakeTmp/CMakeLists.txt:1```
the expression ``Files\Eigen`` contains a slash in the wrong direction. Also the space in ``Program Files`` is not interpreted correctly.

**Comment by HannesSommer** [comment]
This seems wrong usage only. Closing it.
